### ISSUE TITLE
Question about repos being cloned all in the same root folder

### ISSUE THREAD

**Issue by ropinheiro** [davidsarkany/gitlab-backup-util#1]
Nice work! That's what I was trying to do.

But... it clones all repos in the same root folder. I'm trying to understand how can I change the code slightly so that it clones each repo respecting the folder tree in Gitlab. e.g. I have access to two distinct accounts and the repos of those accounts get mixed in the same root folder. Also, in one of the accounts we have a giant folder structure, with subfolders. I can't even say if there are repos with the same name, but different folders. What will happen in those cases?

**Comment by ropinheiro** [comment]
Meanwhile I was inspecting the API and noticed that you could use `full_path` instead of `path` when getting the project's information. I will do some experiments here and will keep you informed.

**Comment by ropinheiro** [comment]
I forked the repo to do my changes and tested them. They seem to be working :) So I issued a pull request for you.

**Comment by davidsarkany** [comment]
Good idea.
Thank you for your contribution.
